framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: 'auto'
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'

        pools:
            rsi.citizens.cache:
                adapter: cache.adapter.redis
                tags: true
            rsi.organizations.cache:
                adapter: cache.adapter.redis
                tags: true
            rsi.ships.cache:
                adapter: cache.adapter.redis

    php_errors:
        log: true
