framework:
    http_client:
        max_host_connections: 6
        scoped_clients:
            rsi.orga_members.client:
                base_uri: 'https://robertsspaceindustries.com'
            rsi.ship_infos.client:
                base_uri: 'https://robertsspaceindustries.com'
