security:
    providers:
        oauth_user_provider:
            id: App\Security\OAuthUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        token:
            pattern: ^/api/(export)
            stateless: true
            guard:
                authenticators: ['App\Security\TokenAuthenticator']
        main:
            anonymous: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: true
            oauth:
                resource_owners:
                    discord: /login/check-discord
                login_path: /login
                use_forward: false
                failure_path: /login
                always_use_default_target_path: true
                default_target_path: '/#/profile'
                oauth_user_provider:
                    service: App\Security\OAuthUserProvider
                remember_me:  true
            logout:
                path: logout
            access_denied_handler: App\Security\ApiAccessDeniedHandler

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
