security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        oauth_user_provider:
            id: hwi_oauth.user.provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            oauth:
                resource_owners:
                    discord: /login/check-discord
                login_path: /login
                use_forward: false
                failure_path: /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider

            logout:
                path: logout

    access_control:
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
