security:
    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'discordId'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        token:
            pattern: ^/(export)
            stateless: true
            guard:
                authenticators: ['App\Security\TokenAuthenticator']
        main:
            anonymous: true
            guard:
                authenticators: ['App\Security\DiscordAuthenticator']
            logout:
                path: logout

    access_control:
        - { path: ^/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,           roles: IS_AUTHENTICATED_FULLY }
