security:
    encoders:
        App\Entity\User:
            algorithm: sodium
            memory_cost: 16384 # 16 MiB
            time_cost: 3
    providers:
        oauth_user_provider:
            id: App\Security\OAuthUserProvider
        user_entity:
            entity:
                class: 'App\Entity\User'
                property: 'email'
        user_entity_username:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build|icons|favicon\.ico|robots\.txt)/
            security: false
        token:
            pattern: ^/api/export$
            stateless: true
            guard:
                provider: oauth_user_provider
                authenticators: ['App\Security\TokenAuthenticator']
        main:
            anonymous: true
            user_checker: App\Security\ConfirmedUserChecker
            switch_user:
                provider: user_entity_username
                role: ROLE_ADMIN
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: true
            form_login:
                provider: user_entity
                login_path: /login
                check_path: /api/login/check-form-login
                success_handler: App\Security\FormLoginSuccessHandler
                failure_handler: App\Security\FormLoginFailureHandler
            oauth:
                resource_owners:
                    discord: /login/check-discord
                login_path: /login
                use_forward: false
                failure_path: /login
                always_use_default_target_path: true
                default_target_path: /profile
                provider: oauth_user_provider
                oauth_user_provider:
                    service: App\Security\OAuthUserProvider
                remember_me:  true
            logout:
                path: logout
            access_denied_handler: App\Security\ApiAccessDeniedHandler

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
