security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        oauth_user_provider:
            id: App\Infrastructure\Security\OAuthUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            oauth:
                resource_owners:
                    discord: /login/check-discord
                login_path: /login
                use_forward: false
                failure_path: /login
                always_use_default_target_path: true
                default_target_path: '/#/profile'

                oauth_user_provider:
                    service: App\Infrastructure\Security\OAuthUserProvider

            logout:
                path: logout

    access_control:
        - { path: ^/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,           roles: IS_AUTHENTICATED_FULLY }
