twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/assets/css': css
        '%kernel.project_dir%/assets/img': img
        '%kernel.project_dir%/assets/fonts': fonts
