version: '3'
networks:
    app: ~
volumes:
    db: ~
    redis: ~
services:
    php:
        build:
            context: ./docker/php
        hostname: php
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            - COMPOSER_CACHE_DIR=/dev/null
        networks:
            - app
    apache:
        image: httpd:2.4
        hostname: apache
        volumes:
            - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./public:/var/www/html/public
        working_dir: /var/www/html
        environment:
            - PHP_HANDLER_HOST=php:9000
        networks:
            - app
        ports:
            - 127.0.0.1:8000:80
    mariadb:
        image: mariadb:10.3
        hostname: mariadb
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        networks:
            - app
        ports:
            - 127.0.0.1:3306:3306
    redis:
        image: redis:5.0-alpine
        hostname: redis
        volumes:
            - redis:/data
        ports:
            - 127.0.0.1:6379:6379
        networks:
            - app
    redis-commander:
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
#        restart: unless-stopped
        environment:
            - REDIS_HOSTS=local:redis:6379
        networks:
            - app
        ports:
            - 127.0.0.1:8081:8081
