version: '3.4'
services:
    php:
        image: registry.fleet-manager.space/fm-php:test
        volumes:
            - .:/app
    apache-test:
        image: registry.fleet-manager.space/fm-apache:test
        volumes:
            - .:/app
        environment:
            - PHP_HANDLER_HOST=php:9000
    mysql:
        image: mysql:5.7
        hostname: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        tmpfs: /var/lib/mysql
        volumes:
            - ./docker/mysql/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
