version: '3.4'
volumes:
    db: ~
    redis: ~
services:
    php:
        build:
            context: .
            target: build_php
            dockerfile: ./docker/Dockerfile
        hostname: php
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    apache:
        build:
            context: .
            target: build_apache
            dockerfile: ./docker/Dockerfile
        hostname: apache
        environment:
            - PHP_HANDLER_HOST=php:9000
    mariadb:
        image: mariadb:10.3
        hostname: mariadb
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
    redis:
        image: redis:5.0-alpine
        hostname: redis
        volumes:
            - redis:/data
    redis-commander:
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
        environment:
            - REDIS_HOSTS=local:redis:6379
    smtp:
        image: namshi/smtp
