version: '3.4'
networks:
    app: ~
volumes:
    db: ~
    redis: ~
services:
    php:
        build:
            context: .
            target: build_php
            dockerfile: ./docker/Dockerfile
        hostname: php
        networks:
            - app
    apache:
        build:
            context: .
            target: build_apache
            dockerfile: ./docker/Dockerfile
        hostname: apache
        environment:
            - PHP_HANDLER_HOST=php:9000
        networks:
            - app
        ports:
            - 127.0.0.1:8000:80
    mariadb:
        build:
            context: .
            target: build_mariadb
            dockerfile: ./docker/Dockerfile
        hostname: mariadb
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        networks:
            - app
        ports:
            - 127.0.0.1:3306:3306
    redis:
        image: redis:5.0-alpine
        hostname: redis
        volumes:
            - redis:/data
        ports:
            - 127.0.0.1:6379:6379
        networks:
            - app
    redis-commander:
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
#        restart: unless-stopped
        environment:
            - REDIS_HOSTS=local:redis:6379
        networks:
            - app
        ports:
            - 127.0.0.1:8081:8081
