monolog:
    handlers:
        streamed:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            channels: ["!event"]
        streamed_debug:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-debug.log"
            level: debug
            channels: ["!event"]
        #######
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
