apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: traefik-sc-fleet-manager
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    tls:
        -
            secretName: sc-fleet-manager-tls-cert
    rules:
        -
            host: sc-fleet-manager.minikube
            http:
                paths:
                    -
                        path: /
                        backend:
                            serviceName: apache-cluster-ip
                            servicePort: web
