logout:
    path: /logout

discord_login:
    path: /login/check-discord

spa_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: home.html.twig

spa:
    path: /{spaPath}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        spaPath: '/'
        template: base.html.twig
    requirements:
        spaPath: '.+'
