services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Service\CitizenInfosProviderInterface: '@App\Service\FakeCitizenInfosProvider'
    App\Service\ShipInfosProviderInterface: '@App\Service\FakeShipInfosProvider'
    App\Service\OrganizationMembersInfosProviderInterface: '@App\Service\FakeOrganizationMembersInfosProvider'

    App\Tests\Controller\ConnectController:
        tags: ['controller.service_arguments']
