parameters:
    env(REDIS_HOST): 'localhost'
    env(REDIS_PORT): 6379
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Kernel.php}'

    redis:
        class: Redis
        calls:
            - [connect, ['%env(REDIS_HOST)%', '%env(REDIS_PORT)%']]

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments: ['@redis']

    Doctrine\Common\Cache\RedisCache:
        calls:
            - [setRedis, ['@redis']]

    App\Service\CitizenInfosProviderInterface: '@App\Service\ApiCitizenInfosProvider'
    App\Service\ShipInfosProviderInterface: '@App\Service\ApiShipInfosProvider'
