parameters:
    env(REDIS_HOST): 'localhost'
    env(REDIS_PORT): 6379
    locale: 'en'
    hwi_oauth.authentication.entry_point.oauth.class: 'App\Security\OAuthEntryPoint'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Kernel.php}'

    redis:
        class: Redis
        calls:
            - [connect, ['%env(REDIS_HOST)%', '%env(REDIS_PORT)%']]

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments: ['@redis']

    Doctrine\Common\Cache\RedisCache:
        calls:
            - [setRedis, ['@redis']]

    App\Service\ShipInfosProviderInterface: '@App\Service\ApiShipInfosProvider'
    App\Service\ApiShipInfosProvider:
        arguments: { '$cache': '@rsi.ships.cache' }

    App\Service\OrganizationInfosProviderInterface: '@App\Service\ApiOrganizationInfosProvider'
    App\Service\ApiOrganizationInfosProvider:
        arguments: { '$cache': '@rsi.organizations.cache' }

    App\Service\CitizenInfosProviderInterface: '@App\Service\ApiCitizenInfosProvider'
    App\Service\ApiCitizenInfosProvider:
        arguments: { '$cache': '@rsi.citizens.cache' }

    App\Listener\TrackConnectionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.controller', method: 'onController' }
