services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Service\CitizenInfosProviderInterface: '@App\Service\FakeCitizenInfosProvider'

    App\Tests\Controller\ConnectController:
        tags: ['controller.service_arguments']
