apiVersion: v1
kind: Pod
metadata:
    name: apache-pod
    labels:
        component: web
spec:
    containers:
        -
            name: apache
            image: ioni/sc-fleet-manager_apache
            ports:
                - containerPort: 80
